server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8


# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/localdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://bobfriend.shop:3306/bobfriend?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: bob123
    password: 1234


#    username: prac
#    password: xkaxka66

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true